// Bundles the MCP server and the Failproof policy into self-contained files.
import { build } from "esbuild";

const common = { bundle: true, platform: "node", format: "esm", target: "node20", logLevel: "info", legalComments: "none" };

await build({
  ...common,
  entryPoints: ["src/server/ap-server.ts"],
  outfile: "dist/ap-server.mjs",
  // Some MCP SDK dependencies still call require(); give ESM a require().
  banner: { js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
});

await build({
  ...common,
  entryPoints: ["src/policy/index.ts"],
  outfile: "dist/cleartopay-policies.mjs",
  external: ["failproofai"],
  banner: { js: "// ClearToPay policy bundle for Failproof AI. Generated by scripts/build.mjs — edit src/policy/*, not this file." },
});
